language: julia
os:
    - linux
    - osx
julia:
    - 1.0
    - 1.1
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
# TODO: Remove before merging.
before_script:
    - julia -e 'using Pkg; Pkg.add(PackageSpec(name="MathOptInterface", rev="master"))'
after_success:
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("Ipopt")); using Coverage; Coveralls.submit(process_folder())'
